# fly.toml app configuration file generated for mave-metrics on 2023-06-09T12:53:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mave-metrics"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[deploy]
  strategy = "rolling"

[env]
  PHX_HOST = "mave-metrics.internal"
  PORT = "3000"
  PRIMARY_REGION = "ams"
  ROOT_URL = "http://mave-metrics.internal"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  ports = []
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 512

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "1m0s"
    restart_limit = 0
