app = "mave-metrics"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "ams"
processes = []

[deploy]
  release_command = "/app/bin/migrate"
  strategy = "bluegreen"

[env]
  PHX_HOST = "metrics.mave.io"
  PORT = "3000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
