app = "mave-metrics"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  strategy = "bluegreen"

[env]
  PRIMARY_REGION = "ams"
  PHX_HOST = "metrics.mave.io"
  PORT = "3000"
  ROOT_URL = "https://metrics.mave.io"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 1024
    soft_limit = 512
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
