# fly.toml app configuration file generated for mave-metrics on 2023-06-09T12:53:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mave-data"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[[vm]]
size = "shared-cpu-2x"

[deploy]
release_command = "/app/bin/migrate"
strategy = "rolling"

[env]
PHX_HOST = "mave-data.internal"
DNS_CLUSTER_QUERY = "mave-data.internal"
PORT = "3000"
PRIMARY_REGION = "ams"
ROOT_URL = "http://mave-data.internal"
RELEASE_COOKIE = "3e0vnhSGgY-ZaVA4n3Djv5OCVpoiR4b2voHB2UvYrL4loe3av2XLQA=="

[[services]]
protocol = "tcp"
internal_port = 3000
processes = ["app"]
[[services.ports]]
port = 3000
[services.concurrency]
type = "connections"
hard_limit = 2048
soft_limit = 1024

[[services.tcp_checks]]
interval = "15s"
timeout = "5s"
grace_period = "1m0s"
restart_limit = 0
